<?php

/**
 * @file
 * Yandex money core module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

define('YAMONEY_CHECK_RESULT_CODE_SUCCESS', 0);
define('YAMONEY_CHECK_RESULT_CODE_ERROR_MD5', 1);
define('YAMONEY_CHECK_RESULT_CODE_ERROR_CUSTOM', 100);
define('YAMONEY_CHECK_RESULT_CODE_ERROR_REQUEST', 200);

/**
 * Implements hook_help().
 */
function yamoney_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ush_search module.
    case 'help.page.yamoney':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Yandex payment services') . '</p>';
      return $output;

    default:
  }
}
